### ISSUE TITLE
Can you make sure this works for both FreeCAD master and Realthunder's Link ?

### ISSUE THREAD

**Issue by luzpaz** [AlansCodeLog/freecad-useful-panel#7]
Looks like you're using Link branch. Does this work in master as well ?

**Comment by AlansCodeLog** [comment]
It does, at least with whatever version of 0.20 I have. It just uses the regular freecad API, there's nothing linkstage specific.

Why, did you have any problems?

**Comment by luzpaz** [comment]
Just checking. It looks like you're using Link branch in the screenshots. Thanks!
